// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank_transactions.proto

package br.com.rbcti.protobuf.artifacts;

public interface BankOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bank.Bank)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 bank_code = 2;</code>
   * @return The bankCode.
   */
  int getBankCode();
}
