// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank_transactions.proto

package br.com.rbcti.protobuf.artifacts;

public interface BankAccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bank.BankAccount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 account_number = 1;</code>
   * @return Whether the accountNumber field is set.
   */
  boolean hasAccountNumber();
  /**
   * <code>optional int32 account_number = 1;</code>
   * @return The accountNumber.
   */
  int getAccountNumber();

  /**
   * <code>optional int32 check_digit = 2;</code>
   * @return Whether the checkDigit field is set.
   */
  boolean hasCheckDigit();
  /**
   * <code>optional int32 check_digit = 2;</code>
   * @return The checkDigit.
   */
  int getCheckDigit();
}
