// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank_transactions.proto

package br.com.rbcti.protobuf.artifacts;

public interface BankTransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bank.BankTransaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .bank.FundTransfer transactions = 1;</code>
   */
  java.util.List<br.com.rbcti.protobuf.artifacts.FundTransfer> 
      getTransactionsList();
  /**
   * <code>repeated .bank.FundTransfer transactions = 1;</code>
   */
  br.com.rbcti.protobuf.artifacts.FundTransfer getTransactions(int index);
  /**
   * <code>repeated .bank.FundTransfer transactions = 1;</code>
   */
  int getTransactionsCount();
  /**
   * <code>repeated .bank.FundTransfer transactions = 1;</code>
   */
  java.util.List<? extends br.com.rbcti.protobuf.artifacts.FundTransferOrBuilder> 
      getTransactionsOrBuilderList();
  /**
   * <code>repeated .bank.FundTransfer transactions = 1;</code>
   */
  br.com.rbcti.protobuf.artifacts.FundTransferOrBuilder getTransactionsOrBuilder(
      int index);
}
