// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank_transactions.proto

package br.com.rbcti.protobuf.artifacts;

public final class BankTransactions {
  private BankTransactions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bank_Bank_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bank_Bank_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bank_BankAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bank_BankAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bank_FundTransfer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bank_FundTransfer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bank_BankTransaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bank_BankTransaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027bank_transactions.proto\022\004bank\032\014common." +
      "proto\"\'\n\004Bank\022\014\n\004name\030\001 \001(\t\022\021\n\tbank_code" +
      "\030\002 \001(\005\"g\n\013BankAccount\022\033\n\016account_number\030" +
      "\001 \001(\005H\000\210\001\001\022\030\n\013check_digit\030\002 \001(\005H\001\210\001\001B\021\n\017" +
      "_account_numberB\016\n\014_check_digit\"\313\002\n\014Fund" +
      "Transfer\022\'\n\rtransfer_date\030\001 \001(\0132\020.common" +
      ".DateTime\022\037\n\013source_bank\030\002 \001(\0132\n.bank.Ba" +
      "nk\022.\n\023source_bank_account\030\003 \001(\0132\021.bank.B" +
      "ankAccount\022$\n\020destination_bank\030\004 \001(\0132\n.b" +
      "ank.Bank\0223\n\030destination_bank_account\030\005 \001" +
      "(\0132\021.bank.BankAccount\022\022\n\nfee_amount\030\006 \001(" +
      "\002\022\027\n\017amount_transfer\030\007 \001(\001\022\034\n\006status\030\010 \001" +
      "(\0162\014.bank.Status\022\033\n\023authentication_code\030" +
      "\t \001(\014\";\n\017BankTransaction\022(\n\014transactions" +
      "\030\001 \003(\0132\022.bank.FundTransfer*2\n\006Status\022\013\n\007" +
      "PENDING\020\000\022\r\n\tCONFIRMED\020\001\022\014\n\010CANCELED\020\002B#" +
      "\n\037br.com.rbcti.protobuf.artifactsP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          br.com.rbcti.protobuf.artifacts.Common.getDescriptor(),
        });
    internal_static_bank_Bank_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bank_Bank_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bank_Bank_descriptor,
        new java.lang.String[] { "Name", "BankCode", });
    internal_static_bank_BankAccount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bank_BankAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bank_BankAccount_descriptor,
        new java.lang.String[] { "AccountNumber", "CheckDigit", "AccountNumber", "CheckDigit", });
    internal_static_bank_FundTransfer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bank_FundTransfer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bank_FundTransfer_descriptor,
        new java.lang.String[] { "TransferDate", "SourceBank", "SourceBankAccount", "DestinationBank", "DestinationBankAccount", "FeeAmount", "AmountTransfer", "Status", "AuthenticationCode", });
    internal_static_bank_BankTransaction_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_bank_BankTransaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bank_BankTransaction_descriptor,
        new java.lang.String[] { "Transactions", });
    br.com.rbcti.protobuf.artifacts.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
