// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package br.com.rbcti.protobuf.artifacts;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_DateTime_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_DateTime_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\006common\"\272\001\n\010DateTime\022\020\n\003d" +
      "ay\030\001 \001(\005H\000\210\001\001\022\022\n\005month\030\002 \001(\005H\001\210\001\001\022\021\n\004yea" +
      "r\030\003 \001(\005H\002\210\001\001\022\021\n\004hour\030\004 \001(\005H\003\210\001\001\022\023\n\006minut" +
      "e\030\005 \001(\005H\004\210\001\001\022\023\n\006second\030\006 \001(\005H\005\210\001\001B\006\n\004_da" +
      "yB\010\n\006_monthB\007\n\005_yearB\007\n\005_hourB\t\n\007_minute" +
      "B\t\n\007_secondB#\n\037br.com.rbcti.protobuf.art" +
      "ifactsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_DateTime_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_DateTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_DateTime_descriptor,
        new java.lang.String[] { "Day", "Month", "Year", "Hour", "Minute", "Second", "Day", "Month", "Year", "Hour", "Minute", "Second", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
