// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package br.com.rbcti.protobuf.artifacts;

/**
 * Protobuf type {@code common.DateTime}
 */
public final class DateTime extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:common.DateTime)
    DateTimeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DateTime.newBuilder() to construct.
  private DateTime(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DateTime() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DateTime();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.rbcti.protobuf.artifacts.Common.internal_static_common_DateTime_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.rbcti.protobuf.artifacts.Common.internal_static_common_DateTime_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.rbcti.protobuf.artifacts.DateTime.class, br.com.rbcti.protobuf.artifacts.DateTime.Builder.class);
  }

  private int bitField0_;
  public static final int DAY_FIELD_NUMBER = 1;
  private int day_ = 0;
  /**
   * <code>optional int32 day = 1;</code>
   * @return Whether the day field is set.
   */
  @java.lang.Override
  public boolean hasDay() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 day = 1;</code>
   * @return The day.
   */
  @java.lang.Override
  public int getDay() {
    return day_;
  }

  public static final int MONTH_FIELD_NUMBER = 2;
  private int month_ = 0;
  /**
   * <code>optional int32 month = 2;</code>
   * @return Whether the month field is set.
   */
  @java.lang.Override
  public boolean hasMonth() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 month = 2;</code>
   * @return The month.
   */
  @java.lang.Override
  public int getMonth() {
    return month_;
  }

  public static final int YEAR_FIELD_NUMBER = 3;
  private int year_ = 0;
  /**
   * <code>optional int32 year = 3;</code>
   * @return Whether the year field is set.
   */
  @java.lang.Override
  public boolean hasYear() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 year = 3;</code>
   * @return The year.
   */
  @java.lang.Override
  public int getYear() {
    return year_;
  }

  public static final int HOUR_FIELD_NUMBER = 4;
  private int hour_ = 0;
  /**
   * <code>optional int32 hour = 4;</code>
   * @return Whether the hour field is set.
   */
  @java.lang.Override
  public boolean hasHour() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional int32 hour = 4;</code>
   * @return The hour.
   */
  @java.lang.Override
  public int getHour() {
    return hour_;
  }

  public static final int MINUTE_FIELD_NUMBER = 5;
  private int minute_ = 0;
  /**
   * <code>optional int32 minute = 5;</code>
   * @return Whether the minute field is set.
   */
  @java.lang.Override
  public boolean hasMinute() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 minute = 5;</code>
   * @return The minute.
   */
  @java.lang.Override
  public int getMinute() {
    return minute_;
  }

  public static final int SECOND_FIELD_NUMBER = 6;
  private int second_ = 0;
  /**
   * <code>optional int32 second = 6;</code>
   * @return Whether the second field is set.
   */
  @java.lang.Override
  public boolean hasSecond() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 second = 6;</code>
   * @return The second.
   */
  @java.lang.Override
  public int getSecond() {
    return second_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, day_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, month_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, year_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeInt32(4, hour_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, minute_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(6, second_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, day_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, month_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, year_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, hour_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, minute_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, second_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.rbcti.protobuf.artifacts.DateTime)) {
      return super.equals(obj);
    }
    br.com.rbcti.protobuf.artifacts.DateTime other = (br.com.rbcti.protobuf.artifacts.DateTime) obj;

    if (hasDay() != other.hasDay()) return false;
    if (hasDay()) {
      if (getDay()
          != other.getDay()) return false;
    }
    if (hasMonth() != other.hasMonth()) return false;
    if (hasMonth()) {
      if (getMonth()
          != other.getMonth()) return false;
    }
    if (hasYear() != other.hasYear()) return false;
    if (hasYear()) {
      if (getYear()
          != other.getYear()) return false;
    }
    if (hasHour() != other.hasHour()) return false;
    if (hasHour()) {
      if (getHour()
          != other.getHour()) return false;
    }
    if (hasMinute() != other.hasMinute()) return false;
    if (hasMinute()) {
      if (getMinute()
          != other.getMinute()) return false;
    }
    if (hasSecond() != other.hasSecond()) return false;
    if (hasSecond()) {
      if (getSecond()
          != other.getSecond()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDay()) {
      hash = (37 * hash) + DAY_FIELD_NUMBER;
      hash = (53 * hash) + getDay();
    }
    if (hasMonth()) {
      hash = (37 * hash) + MONTH_FIELD_NUMBER;
      hash = (53 * hash) + getMonth();
    }
    if (hasYear()) {
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
    }
    if (hasHour()) {
      hash = (37 * hash) + HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getHour();
    }
    if (hasMinute()) {
      hash = (37 * hash) + MINUTE_FIELD_NUMBER;
      hash = (53 * hash) + getMinute();
    }
    if (hasSecond()) {
      hash = (37 * hash) + SECOND_FIELD_NUMBER;
      hash = (53 * hash) + getSecond();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.com.rbcti.protobuf.artifacts.DateTime parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.com.rbcti.protobuf.artifacts.DateTime parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.rbcti.protobuf.artifacts.DateTime parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.rbcti.protobuf.artifacts.DateTime prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code common.DateTime}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.DateTime)
      br.com.rbcti.protobuf.artifacts.DateTimeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.rbcti.protobuf.artifacts.Common.internal_static_common_DateTime_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.rbcti.protobuf.artifacts.Common.internal_static_common_DateTime_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.rbcti.protobuf.artifacts.DateTime.class, br.com.rbcti.protobuf.artifacts.DateTime.Builder.class);
    }

    // Construct using br.com.rbcti.protobuf.artifacts.DateTime.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      day_ = 0;
      month_ = 0;
      year_ = 0;
      hour_ = 0;
      minute_ = 0;
      second_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.rbcti.protobuf.artifacts.Common.internal_static_common_DateTime_descriptor;
    }

    @java.lang.Override
    public br.com.rbcti.protobuf.artifacts.DateTime getDefaultInstanceForType() {
      return br.com.rbcti.protobuf.artifacts.DateTime.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.rbcti.protobuf.artifacts.DateTime build() {
      br.com.rbcti.protobuf.artifacts.DateTime result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.rbcti.protobuf.artifacts.DateTime buildPartial() {
      br.com.rbcti.protobuf.artifacts.DateTime result = new br.com.rbcti.protobuf.artifacts.DateTime(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.com.rbcti.protobuf.artifacts.DateTime result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.day_ = day_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.month_ = month_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.year_ = year_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hour_ = hour_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.minute_ = minute_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.second_ = second_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.rbcti.protobuf.artifacts.DateTime) {
        return mergeFrom((br.com.rbcti.protobuf.artifacts.DateTime)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.rbcti.protobuf.artifacts.DateTime other) {
      if (other == br.com.rbcti.protobuf.artifacts.DateTime.getDefaultInstance()) return this;
      if (other.hasDay()) {
        setDay(other.getDay());
      }
      if (other.hasMonth()) {
        setMonth(other.getMonth());
      }
      if (other.hasYear()) {
        setYear(other.getYear());
      }
      if (other.hasHour()) {
        setHour(other.getHour());
      }
      if (other.hasMinute()) {
        setMinute(other.getMinute());
      }
      if (other.hasSecond()) {
        setSecond(other.getSecond());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              day_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              month_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              year_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              hour_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              minute_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              second_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int day_ ;
    /**
     * <code>optional int32 day = 1;</code>
     * @return Whether the day field is set.
     */
    @java.lang.Override
    public boolean hasDay() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 day = 1;</code>
     * @return The day.
     */
    @java.lang.Override
    public int getDay() {
      return day_;
    }
    /**
     * <code>optional int32 day = 1;</code>
     * @param value The day to set.
     * @return This builder for chaining.
     */
    public Builder setDay(int value) {

      day_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 day = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDay() {
      bitField0_ = (bitField0_ & ~0x00000001);
      day_ = 0;
      onChanged();
      return this;
    }

    private int month_ ;
    /**
     * <code>optional int32 month = 2;</code>
     * @return Whether the month field is set.
     */
    @java.lang.Override
    public boolean hasMonth() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 month = 2;</code>
     * @return The month.
     */
    @java.lang.Override
    public int getMonth() {
      return month_;
    }
    /**
     * <code>optional int32 month = 2;</code>
     * @param value The month to set.
     * @return This builder for chaining.
     */
    public Builder setMonth(int value) {

      month_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 month = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMonth() {
      bitField0_ = (bitField0_ & ~0x00000002);
      month_ = 0;
      onChanged();
      return this;
    }

    private int year_ ;
    /**
     * <code>optional int32 year = 3;</code>
     * @return Whether the year field is set.
     */
    @java.lang.Override
    public boolean hasYear() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 year = 3;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }
    /**
     * <code>optional int32 year = 3;</code>
     * @param value The year to set.
     * @return This builder for chaining.
     */
    public Builder setYear(int value) {

      year_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 year = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearYear() {
      bitField0_ = (bitField0_ & ~0x00000004);
      year_ = 0;
      onChanged();
      return this;
    }

    private int hour_ ;
    /**
     * <code>optional int32 hour = 4;</code>
     * @return Whether the hour field is set.
     */
    @java.lang.Override
    public boolean hasHour() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 hour = 4;</code>
     * @return The hour.
     */
    @java.lang.Override
    public int getHour() {
      return hour_;
    }
    /**
     * <code>optional int32 hour = 4;</code>
     * @param value The hour to set.
     * @return This builder for chaining.
     */
    public Builder setHour(int value) {

      hour_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 hour = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHour() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hour_ = 0;
      onChanged();
      return this;
    }

    private int minute_ ;
    /**
     * <code>optional int32 minute = 5;</code>
     * @return Whether the minute field is set.
     */
    @java.lang.Override
    public boolean hasMinute() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 minute = 5;</code>
     * @return The minute.
     */
    @java.lang.Override
    public int getMinute() {
      return minute_;
    }
    /**
     * <code>optional int32 minute = 5;</code>
     * @param value The minute to set.
     * @return This builder for chaining.
     */
    public Builder setMinute(int value) {

      minute_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 minute = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinute() {
      bitField0_ = (bitField0_ & ~0x00000010);
      minute_ = 0;
      onChanged();
      return this;
    }

    private int second_ ;
    /**
     * <code>optional int32 second = 6;</code>
     * @return Whether the second field is set.
     */
    @java.lang.Override
    public boolean hasSecond() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 second = 6;</code>
     * @return The second.
     */
    @java.lang.Override
    public int getSecond() {
      return second_;
    }
    /**
     * <code>optional int32 second = 6;</code>
     * @param value The second to set.
     * @return This builder for chaining.
     */
    public Builder setSecond(int value) {

      second_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 second = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecond() {
      bitField0_ = (bitField0_ & ~0x00000020);
      second_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:common.DateTime)
  }

  // @@protoc_insertion_point(class_scope:common.DateTime)
  private static final br.com.rbcti.protobuf.artifacts.DateTime DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.rbcti.protobuf.artifacts.DateTime();
  }

  public static br.com.rbcti.protobuf.artifacts.DateTime getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DateTime>
      PARSER = new com.google.protobuf.AbstractParser<DateTime>() {
    @java.lang.Override
    public DateTime parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DateTime> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DateTime> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.DateTime getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

