// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank_transactions.proto

package br.com.rbcti.protobuf.artifacts;

/**
 * Protobuf type {@code bank.FundTransfer}
 */
public final class FundTransfer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bank.FundTransfer)
    FundTransferOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FundTransfer.newBuilder() to construct.
  private FundTransfer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FundTransfer() {
    status_ = 0;
    authenticationCode_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FundTransfer();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.rbcti.protobuf.artifacts.BankTransactions.internal_static_bank_FundTransfer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.rbcti.protobuf.artifacts.BankTransactions.internal_static_bank_FundTransfer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.rbcti.protobuf.artifacts.FundTransfer.class, br.com.rbcti.protobuf.artifacts.FundTransfer.Builder.class);
  }

  private int bitField0_;
  public static final int TRANSFER_DATE_FIELD_NUMBER = 1;
  private br.com.rbcti.protobuf.artifacts.DateTime transferDate_;
  /**
   * <code>.common.DateTime transfer_date = 1;</code>
   * @return Whether the transferDate field is set.
   */
  @java.lang.Override
  public boolean hasTransferDate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.common.DateTime transfer_date = 1;</code>
   * @return The transferDate.
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.DateTime getTransferDate() {
    return transferDate_ == null ? br.com.rbcti.protobuf.artifacts.DateTime.getDefaultInstance() : transferDate_;
  }
  /**
   * <code>.common.DateTime transfer_date = 1;</code>
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.DateTimeOrBuilder getTransferDateOrBuilder() {
    return transferDate_ == null ? br.com.rbcti.protobuf.artifacts.DateTime.getDefaultInstance() : transferDate_;
  }

  public static final int SOURCE_BANK_FIELD_NUMBER = 2;
  private br.com.rbcti.protobuf.artifacts.Bank sourceBank_;
  /**
   * <code>.bank.Bank source_bank = 2;</code>
   * @return Whether the sourceBank field is set.
   */
  @java.lang.Override
  public boolean hasSourceBank() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.bank.Bank source_bank = 2;</code>
   * @return The sourceBank.
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.Bank getSourceBank() {
    return sourceBank_ == null ? br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance() : sourceBank_;
  }
  /**
   * <code>.bank.Bank source_bank = 2;</code>
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.BankOrBuilder getSourceBankOrBuilder() {
    return sourceBank_ == null ? br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance() : sourceBank_;
  }

  public static final int SOURCE_BANK_ACCOUNT_FIELD_NUMBER = 3;
  private br.com.rbcti.protobuf.artifacts.BankAccount sourceBankAccount_;
  /**
   * <code>.bank.BankAccount source_bank_account = 3;</code>
   * @return Whether the sourceBankAccount field is set.
   */
  @java.lang.Override
  public boolean hasSourceBankAccount() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.bank.BankAccount source_bank_account = 3;</code>
   * @return The sourceBankAccount.
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.BankAccount getSourceBankAccount() {
    return sourceBankAccount_ == null ? br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance() : sourceBankAccount_;
  }
  /**
   * <code>.bank.BankAccount source_bank_account = 3;</code>
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder getSourceBankAccountOrBuilder() {
    return sourceBankAccount_ == null ? br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance() : sourceBankAccount_;
  }

  public static final int DESTINATION_BANK_FIELD_NUMBER = 4;
  private br.com.rbcti.protobuf.artifacts.Bank destinationBank_;
  /**
   * <code>.bank.Bank destination_bank = 4;</code>
   * @return Whether the destinationBank field is set.
   */
  @java.lang.Override
  public boolean hasDestinationBank() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.bank.Bank destination_bank = 4;</code>
   * @return The destinationBank.
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.Bank getDestinationBank() {
    return destinationBank_ == null ? br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance() : destinationBank_;
  }
  /**
   * <code>.bank.Bank destination_bank = 4;</code>
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.BankOrBuilder getDestinationBankOrBuilder() {
    return destinationBank_ == null ? br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance() : destinationBank_;
  }

  public static final int DESTINATION_BANK_ACCOUNT_FIELD_NUMBER = 5;
  private br.com.rbcti.protobuf.artifacts.BankAccount destinationBankAccount_;
  /**
   * <code>.bank.BankAccount destination_bank_account = 5;</code>
   * @return Whether the destinationBankAccount field is set.
   */
  @java.lang.Override
  public boolean hasDestinationBankAccount() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.bank.BankAccount destination_bank_account = 5;</code>
   * @return The destinationBankAccount.
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.BankAccount getDestinationBankAccount() {
    return destinationBankAccount_ == null ? br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance() : destinationBankAccount_;
  }
  /**
   * <code>.bank.BankAccount destination_bank_account = 5;</code>
   */
  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder getDestinationBankAccountOrBuilder() {
    return destinationBankAccount_ == null ? br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance() : destinationBankAccount_;
  }

  public static final int FEE_AMOUNT_FIELD_NUMBER = 6;
  private float feeAmount_ = 0F;
  /**
   * <code>float fee_amount = 6;</code>
   * @return The feeAmount.
   */
  @java.lang.Override
  public float getFeeAmount() {
    return feeAmount_;
  }

  public static final int AMOUNT_TRANSFER_FIELD_NUMBER = 7;
  private double amountTransfer_ = 0D;
  /**
   * <code>double amount_transfer = 7;</code>
   * @return The amountTransfer.
   */
  @java.lang.Override
  public double getAmountTransfer() {
    return amountTransfer_;
  }

  public static final int STATUS_FIELD_NUMBER = 8;
  private int status_ = 0;
  /**
   * <code>.bank.Status status = 8;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.bank.Status status = 8;</code>
   * @return The status.
   */
  @java.lang.Override public br.com.rbcti.protobuf.artifacts.Status getStatus() {
    br.com.rbcti.protobuf.artifacts.Status result = br.com.rbcti.protobuf.artifacts.Status.forNumber(status_);
    return result == null ? br.com.rbcti.protobuf.artifacts.Status.UNRECOGNIZED : result;
  }

  public static final int AUTHENTICATION_CODE_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString authenticationCode_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes authentication_code = 9;</code>
   * @return The authenticationCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getAuthenticationCode() {
    return authenticationCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTransferDate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getSourceBank());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getSourceBankAccount());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getDestinationBank());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getDestinationBankAccount());
    }
    if (java.lang.Float.floatToRawIntBits(feeAmount_) != 0) {
      output.writeFloat(6, feeAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(amountTransfer_) != 0) {
      output.writeDouble(7, amountTransfer_);
    }
    if (status_ != br.com.rbcti.protobuf.artifacts.Status.PENDING.getNumber()) {
      output.writeEnum(8, status_);
    }
    if (!authenticationCode_.isEmpty()) {
      output.writeBytes(9, authenticationCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTransferDate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getSourceBank());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSourceBankAccount());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDestinationBank());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDestinationBankAccount());
    }
    if (java.lang.Float.floatToRawIntBits(feeAmount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, feeAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(amountTransfer_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, amountTransfer_);
    }
    if (status_ != br.com.rbcti.protobuf.artifacts.Status.PENDING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, status_);
    }
    if (!authenticationCode_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, authenticationCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.rbcti.protobuf.artifacts.FundTransfer)) {
      return super.equals(obj);
    }
    br.com.rbcti.protobuf.artifacts.FundTransfer other = (br.com.rbcti.protobuf.artifacts.FundTransfer) obj;

    if (hasTransferDate() != other.hasTransferDate()) return false;
    if (hasTransferDate()) {
      if (!getTransferDate()
          .equals(other.getTransferDate())) return false;
    }
    if (hasSourceBank() != other.hasSourceBank()) return false;
    if (hasSourceBank()) {
      if (!getSourceBank()
          .equals(other.getSourceBank())) return false;
    }
    if (hasSourceBankAccount() != other.hasSourceBankAccount()) return false;
    if (hasSourceBankAccount()) {
      if (!getSourceBankAccount()
          .equals(other.getSourceBankAccount())) return false;
    }
    if (hasDestinationBank() != other.hasDestinationBank()) return false;
    if (hasDestinationBank()) {
      if (!getDestinationBank()
          .equals(other.getDestinationBank())) return false;
    }
    if (hasDestinationBankAccount() != other.hasDestinationBankAccount()) return false;
    if (hasDestinationBankAccount()) {
      if (!getDestinationBankAccount()
          .equals(other.getDestinationBankAccount())) return false;
    }
    if (java.lang.Float.floatToIntBits(getFeeAmount())
        != java.lang.Float.floatToIntBits(
            other.getFeeAmount())) return false;
    if (java.lang.Double.doubleToLongBits(getAmountTransfer())
        != java.lang.Double.doubleToLongBits(
            other.getAmountTransfer())) return false;
    if (status_ != other.status_) return false;
    if (!getAuthenticationCode()
        .equals(other.getAuthenticationCode())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTransferDate()) {
      hash = (37 * hash) + TRANSFER_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getTransferDate().hashCode();
    }
    if (hasSourceBank()) {
      hash = (37 * hash) + SOURCE_BANK_FIELD_NUMBER;
      hash = (53 * hash) + getSourceBank().hashCode();
    }
    if (hasSourceBankAccount()) {
      hash = (37 * hash) + SOURCE_BANK_ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getSourceBankAccount().hashCode();
    }
    if (hasDestinationBank()) {
      hash = (37 * hash) + DESTINATION_BANK_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationBank().hashCode();
    }
    if (hasDestinationBankAccount()) {
      hash = (37 * hash) + DESTINATION_BANK_ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationBankAccount().hashCode();
    }
    hash = (37 * hash) + FEE_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getFeeAmount());
    hash = (37 * hash) + AMOUNT_TRANSFER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmountTransfer()));
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + AUTHENTICATION_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getAuthenticationCode().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.rbcti.protobuf.artifacts.FundTransfer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.rbcti.protobuf.artifacts.FundTransfer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bank.FundTransfer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bank.FundTransfer)
      br.com.rbcti.protobuf.artifacts.FundTransferOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.rbcti.protobuf.artifacts.BankTransactions.internal_static_bank_FundTransfer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.rbcti.protobuf.artifacts.BankTransactions.internal_static_bank_FundTransfer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.rbcti.protobuf.artifacts.FundTransfer.class, br.com.rbcti.protobuf.artifacts.FundTransfer.Builder.class);
    }

    // Construct using br.com.rbcti.protobuf.artifacts.FundTransfer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTransferDateFieldBuilder();
        getSourceBankFieldBuilder();
        getSourceBankAccountFieldBuilder();
        getDestinationBankFieldBuilder();
        getDestinationBankAccountFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      transferDate_ = null;
      if (transferDateBuilder_ != null) {
        transferDateBuilder_.dispose();
        transferDateBuilder_ = null;
      }
      sourceBank_ = null;
      if (sourceBankBuilder_ != null) {
        sourceBankBuilder_.dispose();
        sourceBankBuilder_ = null;
      }
      sourceBankAccount_ = null;
      if (sourceBankAccountBuilder_ != null) {
        sourceBankAccountBuilder_.dispose();
        sourceBankAccountBuilder_ = null;
      }
      destinationBank_ = null;
      if (destinationBankBuilder_ != null) {
        destinationBankBuilder_.dispose();
        destinationBankBuilder_ = null;
      }
      destinationBankAccount_ = null;
      if (destinationBankAccountBuilder_ != null) {
        destinationBankAccountBuilder_.dispose();
        destinationBankAccountBuilder_ = null;
      }
      feeAmount_ = 0F;
      amountTransfer_ = 0D;
      status_ = 0;
      authenticationCode_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.rbcti.protobuf.artifacts.BankTransactions.internal_static_bank_FundTransfer_descriptor;
    }

    @java.lang.Override
    public br.com.rbcti.protobuf.artifacts.FundTransfer getDefaultInstanceForType() {
      return br.com.rbcti.protobuf.artifacts.FundTransfer.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.rbcti.protobuf.artifacts.FundTransfer build() {
      br.com.rbcti.protobuf.artifacts.FundTransfer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.rbcti.protobuf.artifacts.FundTransfer buildPartial() {
      br.com.rbcti.protobuf.artifacts.FundTransfer result = new br.com.rbcti.protobuf.artifacts.FundTransfer(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.com.rbcti.protobuf.artifacts.FundTransfer result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.transferDate_ = transferDateBuilder_ == null
            ? transferDate_
            : transferDateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sourceBank_ = sourceBankBuilder_ == null
            ? sourceBank_
            : sourceBankBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sourceBankAccount_ = sourceBankAccountBuilder_ == null
            ? sourceBankAccount_
            : sourceBankAccountBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.destinationBank_ = destinationBankBuilder_ == null
            ? destinationBank_
            : destinationBankBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.destinationBankAccount_ = destinationBankAccountBuilder_ == null
            ? destinationBankAccount_
            : destinationBankAccountBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.feeAmount_ = feeAmount_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.amountTransfer_ = amountTransfer_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.authenticationCode_ = authenticationCode_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.rbcti.protobuf.artifacts.FundTransfer) {
        return mergeFrom((br.com.rbcti.protobuf.artifacts.FundTransfer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.rbcti.protobuf.artifacts.FundTransfer other) {
      if (other == br.com.rbcti.protobuf.artifacts.FundTransfer.getDefaultInstance()) return this;
      if (other.hasTransferDate()) {
        mergeTransferDate(other.getTransferDate());
      }
      if (other.hasSourceBank()) {
        mergeSourceBank(other.getSourceBank());
      }
      if (other.hasSourceBankAccount()) {
        mergeSourceBankAccount(other.getSourceBankAccount());
      }
      if (other.hasDestinationBank()) {
        mergeDestinationBank(other.getDestinationBank());
      }
      if (other.hasDestinationBankAccount()) {
        mergeDestinationBankAccount(other.getDestinationBankAccount());
      }
      if (other.getFeeAmount() != 0F) {
        setFeeAmount(other.getFeeAmount());
      }
      if (other.getAmountTransfer() != 0D) {
        setAmountTransfer(other.getAmountTransfer());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getAuthenticationCode() != com.google.protobuf.ByteString.EMPTY) {
        setAuthenticationCode(other.getAuthenticationCode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTransferDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getSourceBankFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSourceBankAccountFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getDestinationBankFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getDestinationBankAccountFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 53: {
              feeAmount_ = input.readFloat();
              bitField0_ |= 0x00000020;
              break;
            } // case 53
            case 57: {
              amountTransfer_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 64: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              authenticationCode_ = input.readBytes();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private br.com.rbcti.protobuf.artifacts.DateTime transferDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.DateTime, br.com.rbcti.protobuf.artifacts.DateTime.Builder, br.com.rbcti.protobuf.artifacts.DateTimeOrBuilder> transferDateBuilder_;
    /**
     * <code>.common.DateTime transfer_date = 1;</code>
     * @return Whether the transferDate field is set.
     */
    public boolean hasTransferDate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.common.DateTime transfer_date = 1;</code>
     * @return The transferDate.
     */
    public br.com.rbcti.protobuf.artifacts.DateTime getTransferDate() {
      if (transferDateBuilder_ == null) {
        return transferDate_ == null ? br.com.rbcti.protobuf.artifacts.DateTime.getDefaultInstance() : transferDate_;
      } else {
        return transferDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.DateTime transfer_date = 1;</code>
     */
    public Builder setTransferDate(br.com.rbcti.protobuf.artifacts.DateTime value) {
      if (transferDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        transferDate_ = value;
      } else {
        transferDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.common.DateTime transfer_date = 1;</code>
     */
    public Builder setTransferDate(
        br.com.rbcti.protobuf.artifacts.DateTime.Builder builderForValue) {
      if (transferDateBuilder_ == null) {
        transferDate_ = builderForValue.build();
      } else {
        transferDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.common.DateTime transfer_date = 1;</code>
     */
    public Builder mergeTransferDate(br.com.rbcti.protobuf.artifacts.DateTime value) {
      if (transferDateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          transferDate_ != null &&
          transferDate_ != br.com.rbcti.protobuf.artifacts.DateTime.getDefaultInstance()) {
          getTransferDateBuilder().mergeFrom(value);
        } else {
          transferDate_ = value;
        }
      } else {
        transferDateBuilder_.mergeFrom(value);
      }
      if (transferDate_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.common.DateTime transfer_date = 1;</code>
     */
    public Builder clearTransferDate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      transferDate_ = null;
      if (transferDateBuilder_ != null) {
        transferDateBuilder_.dispose();
        transferDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.common.DateTime transfer_date = 1;</code>
     */
    public br.com.rbcti.protobuf.artifacts.DateTime.Builder getTransferDateBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTransferDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.DateTime transfer_date = 1;</code>
     */
    public br.com.rbcti.protobuf.artifacts.DateTimeOrBuilder getTransferDateOrBuilder() {
      if (transferDateBuilder_ != null) {
        return transferDateBuilder_.getMessageOrBuilder();
      } else {
        return transferDate_ == null ?
            br.com.rbcti.protobuf.artifacts.DateTime.getDefaultInstance() : transferDate_;
      }
    }
    /**
     * <code>.common.DateTime transfer_date = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.DateTime, br.com.rbcti.protobuf.artifacts.DateTime.Builder, br.com.rbcti.protobuf.artifacts.DateTimeOrBuilder> 
        getTransferDateFieldBuilder() {
      if (transferDateBuilder_ == null) {
        transferDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.rbcti.protobuf.artifacts.DateTime, br.com.rbcti.protobuf.artifacts.DateTime.Builder, br.com.rbcti.protobuf.artifacts.DateTimeOrBuilder>(
                getTransferDate(),
                getParentForChildren(),
                isClean());
        transferDate_ = null;
      }
      return transferDateBuilder_;
    }

    private br.com.rbcti.protobuf.artifacts.Bank sourceBank_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.Bank, br.com.rbcti.protobuf.artifacts.Bank.Builder, br.com.rbcti.protobuf.artifacts.BankOrBuilder> sourceBankBuilder_;
    /**
     * <code>.bank.Bank source_bank = 2;</code>
     * @return Whether the sourceBank field is set.
     */
    public boolean hasSourceBank() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.bank.Bank source_bank = 2;</code>
     * @return The sourceBank.
     */
    public br.com.rbcti.protobuf.artifacts.Bank getSourceBank() {
      if (sourceBankBuilder_ == null) {
        return sourceBank_ == null ? br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance() : sourceBank_;
      } else {
        return sourceBankBuilder_.getMessage();
      }
    }
    /**
     * <code>.bank.Bank source_bank = 2;</code>
     */
    public Builder setSourceBank(br.com.rbcti.protobuf.artifacts.Bank value) {
      if (sourceBankBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sourceBank_ = value;
      } else {
        sourceBankBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.bank.Bank source_bank = 2;</code>
     */
    public Builder setSourceBank(
        br.com.rbcti.protobuf.artifacts.Bank.Builder builderForValue) {
      if (sourceBankBuilder_ == null) {
        sourceBank_ = builderForValue.build();
      } else {
        sourceBankBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.bank.Bank source_bank = 2;</code>
     */
    public Builder mergeSourceBank(br.com.rbcti.protobuf.artifacts.Bank value) {
      if (sourceBankBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          sourceBank_ != null &&
          sourceBank_ != br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance()) {
          getSourceBankBuilder().mergeFrom(value);
        } else {
          sourceBank_ = value;
        }
      } else {
        sourceBankBuilder_.mergeFrom(value);
      }
      if (sourceBank_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bank.Bank source_bank = 2;</code>
     */
    public Builder clearSourceBank() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sourceBank_ = null;
      if (sourceBankBuilder_ != null) {
        sourceBankBuilder_.dispose();
        sourceBankBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bank.Bank source_bank = 2;</code>
     */
    public br.com.rbcti.protobuf.artifacts.Bank.Builder getSourceBankBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getSourceBankFieldBuilder().getBuilder();
    }
    /**
     * <code>.bank.Bank source_bank = 2;</code>
     */
    public br.com.rbcti.protobuf.artifacts.BankOrBuilder getSourceBankOrBuilder() {
      if (sourceBankBuilder_ != null) {
        return sourceBankBuilder_.getMessageOrBuilder();
      } else {
        return sourceBank_ == null ?
            br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance() : sourceBank_;
      }
    }
    /**
     * <code>.bank.Bank source_bank = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.Bank, br.com.rbcti.protobuf.artifacts.Bank.Builder, br.com.rbcti.protobuf.artifacts.BankOrBuilder> 
        getSourceBankFieldBuilder() {
      if (sourceBankBuilder_ == null) {
        sourceBankBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.rbcti.protobuf.artifacts.Bank, br.com.rbcti.protobuf.artifacts.Bank.Builder, br.com.rbcti.protobuf.artifacts.BankOrBuilder>(
                getSourceBank(),
                getParentForChildren(),
                isClean());
        sourceBank_ = null;
      }
      return sourceBankBuilder_;
    }

    private br.com.rbcti.protobuf.artifacts.BankAccount sourceBankAccount_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.BankAccount, br.com.rbcti.protobuf.artifacts.BankAccount.Builder, br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder> sourceBankAccountBuilder_;
    /**
     * <code>.bank.BankAccount source_bank_account = 3;</code>
     * @return Whether the sourceBankAccount field is set.
     */
    public boolean hasSourceBankAccount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.bank.BankAccount source_bank_account = 3;</code>
     * @return The sourceBankAccount.
     */
    public br.com.rbcti.protobuf.artifacts.BankAccount getSourceBankAccount() {
      if (sourceBankAccountBuilder_ == null) {
        return sourceBankAccount_ == null ? br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance() : sourceBankAccount_;
      } else {
        return sourceBankAccountBuilder_.getMessage();
      }
    }
    /**
     * <code>.bank.BankAccount source_bank_account = 3;</code>
     */
    public Builder setSourceBankAccount(br.com.rbcti.protobuf.artifacts.BankAccount value) {
      if (sourceBankAccountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sourceBankAccount_ = value;
      } else {
        sourceBankAccountBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.bank.BankAccount source_bank_account = 3;</code>
     */
    public Builder setSourceBankAccount(
        br.com.rbcti.protobuf.artifacts.BankAccount.Builder builderForValue) {
      if (sourceBankAccountBuilder_ == null) {
        sourceBankAccount_ = builderForValue.build();
      } else {
        sourceBankAccountBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.bank.BankAccount source_bank_account = 3;</code>
     */
    public Builder mergeSourceBankAccount(br.com.rbcti.protobuf.artifacts.BankAccount value) {
      if (sourceBankAccountBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          sourceBankAccount_ != null &&
          sourceBankAccount_ != br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance()) {
          getSourceBankAccountBuilder().mergeFrom(value);
        } else {
          sourceBankAccount_ = value;
        }
      } else {
        sourceBankAccountBuilder_.mergeFrom(value);
      }
      if (sourceBankAccount_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bank.BankAccount source_bank_account = 3;</code>
     */
    public Builder clearSourceBankAccount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sourceBankAccount_ = null;
      if (sourceBankAccountBuilder_ != null) {
        sourceBankAccountBuilder_.dispose();
        sourceBankAccountBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bank.BankAccount source_bank_account = 3;</code>
     */
    public br.com.rbcti.protobuf.artifacts.BankAccount.Builder getSourceBankAccountBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getSourceBankAccountFieldBuilder().getBuilder();
    }
    /**
     * <code>.bank.BankAccount source_bank_account = 3;</code>
     */
    public br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder getSourceBankAccountOrBuilder() {
      if (sourceBankAccountBuilder_ != null) {
        return sourceBankAccountBuilder_.getMessageOrBuilder();
      } else {
        return sourceBankAccount_ == null ?
            br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance() : sourceBankAccount_;
      }
    }
    /**
     * <code>.bank.BankAccount source_bank_account = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.BankAccount, br.com.rbcti.protobuf.artifacts.BankAccount.Builder, br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder> 
        getSourceBankAccountFieldBuilder() {
      if (sourceBankAccountBuilder_ == null) {
        sourceBankAccountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.rbcti.protobuf.artifacts.BankAccount, br.com.rbcti.protobuf.artifacts.BankAccount.Builder, br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder>(
                getSourceBankAccount(),
                getParentForChildren(),
                isClean());
        sourceBankAccount_ = null;
      }
      return sourceBankAccountBuilder_;
    }

    private br.com.rbcti.protobuf.artifacts.Bank destinationBank_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.Bank, br.com.rbcti.protobuf.artifacts.Bank.Builder, br.com.rbcti.protobuf.artifacts.BankOrBuilder> destinationBankBuilder_;
    /**
     * <code>.bank.Bank destination_bank = 4;</code>
     * @return Whether the destinationBank field is set.
     */
    public boolean hasDestinationBank() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.bank.Bank destination_bank = 4;</code>
     * @return The destinationBank.
     */
    public br.com.rbcti.protobuf.artifacts.Bank getDestinationBank() {
      if (destinationBankBuilder_ == null) {
        return destinationBank_ == null ? br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance() : destinationBank_;
      } else {
        return destinationBankBuilder_.getMessage();
      }
    }
    /**
     * <code>.bank.Bank destination_bank = 4;</code>
     */
    public Builder setDestinationBank(br.com.rbcti.protobuf.artifacts.Bank value) {
      if (destinationBankBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destinationBank_ = value;
      } else {
        destinationBankBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.bank.Bank destination_bank = 4;</code>
     */
    public Builder setDestinationBank(
        br.com.rbcti.protobuf.artifacts.Bank.Builder builderForValue) {
      if (destinationBankBuilder_ == null) {
        destinationBank_ = builderForValue.build();
      } else {
        destinationBankBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.bank.Bank destination_bank = 4;</code>
     */
    public Builder mergeDestinationBank(br.com.rbcti.protobuf.artifacts.Bank value) {
      if (destinationBankBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          destinationBank_ != null &&
          destinationBank_ != br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance()) {
          getDestinationBankBuilder().mergeFrom(value);
        } else {
          destinationBank_ = value;
        }
      } else {
        destinationBankBuilder_.mergeFrom(value);
      }
      if (destinationBank_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bank.Bank destination_bank = 4;</code>
     */
    public Builder clearDestinationBank() {
      bitField0_ = (bitField0_ & ~0x00000008);
      destinationBank_ = null;
      if (destinationBankBuilder_ != null) {
        destinationBankBuilder_.dispose();
        destinationBankBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bank.Bank destination_bank = 4;</code>
     */
    public br.com.rbcti.protobuf.artifacts.Bank.Builder getDestinationBankBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getDestinationBankFieldBuilder().getBuilder();
    }
    /**
     * <code>.bank.Bank destination_bank = 4;</code>
     */
    public br.com.rbcti.protobuf.artifacts.BankOrBuilder getDestinationBankOrBuilder() {
      if (destinationBankBuilder_ != null) {
        return destinationBankBuilder_.getMessageOrBuilder();
      } else {
        return destinationBank_ == null ?
            br.com.rbcti.protobuf.artifacts.Bank.getDefaultInstance() : destinationBank_;
      }
    }
    /**
     * <code>.bank.Bank destination_bank = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.Bank, br.com.rbcti.protobuf.artifacts.Bank.Builder, br.com.rbcti.protobuf.artifacts.BankOrBuilder> 
        getDestinationBankFieldBuilder() {
      if (destinationBankBuilder_ == null) {
        destinationBankBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.rbcti.protobuf.artifacts.Bank, br.com.rbcti.protobuf.artifacts.Bank.Builder, br.com.rbcti.protobuf.artifacts.BankOrBuilder>(
                getDestinationBank(),
                getParentForChildren(),
                isClean());
        destinationBank_ = null;
      }
      return destinationBankBuilder_;
    }

    private br.com.rbcti.protobuf.artifacts.BankAccount destinationBankAccount_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.BankAccount, br.com.rbcti.protobuf.artifacts.BankAccount.Builder, br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder> destinationBankAccountBuilder_;
    /**
     * <code>.bank.BankAccount destination_bank_account = 5;</code>
     * @return Whether the destinationBankAccount field is set.
     */
    public boolean hasDestinationBankAccount() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.bank.BankAccount destination_bank_account = 5;</code>
     * @return The destinationBankAccount.
     */
    public br.com.rbcti.protobuf.artifacts.BankAccount getDestinationBankAccount() {
      if (destinationBankAccountBuilder_ == null) {
        return destinationBankAccount_ == null ? br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance() : destinationBankAccount_;
      } else {
        return destinationBankAccountBuilder_.getMessage();
      }
    }
    /**
     * <code>.bank.BankAccount destination_bank_account = 5;</code>
     */
    public Builder setDestinationBankAccount(br.com.rbcti.protobuf.artifacts.BankAccount value) {
      if (destinationBankAccountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destinationBankAccount_ = value;
      } else {
        destinationBankAccountBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.bank.BankAccount destination_bank_account = 5;</code>
     */
    public Builder setDestinationBankAccount(
        br.com.rbcti.protobuf.artifacts.BankAccount.Builder builderForValue) {
      if (destinationBankAccountBuilder_ == null) {
        destinationBankAccount_ = builderForValue.build();
      } else {
        destinationBankAccountBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.bank.BankAccount destination_bank_account = 5;</code>
     */
    public Builder mergeDestinationBankAccount(br.com.rbcti.protobuf.artifacts.BankAccount value) {
      if (destinationBankAccountBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          destinationBankAccount_ != null &&
          destinationBankAccount_ != br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance()) {
          getDestinationBankAccountBuilder().mergeFrom(value);
        } else {
          destinationBankAccount_ = value;
        }
      } else {
        destinationBankAccountBuilder_.mergeFrom(value);
      }
      if (destinationBankAccount_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.bank.BankAccount destination_bank_account = 5;</code>
     */
    public Builder clearDestinationBankAccount() {
      bitField0_ = (bitField0_ & ~0x00000010);
      destinationBankAccount_ = null;
      if (destinationBankAccountBuilder_ != null) {
        destinationBankAccountBuilder_.dispose();
        destinationBankAccountBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.bank.BankAccount destination_bank_account = 5;</code>
     */
    public br.com.rbcti.protobuf.artifacts.BankAccount.Builder getDestinationBankAccountBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getDestinationBankAccountFieldBuilder().getBuilder();
    }
    /**
     * <code>.bank.BankAccount destination_bank_account = 5;</code>
     */
    public br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder getDestinationBankAccountOrBuilder() {
      if (destinationBankAccountBuilder_ != null) {
        return destinationBankAccountBuilder_.getMessageOrBuilder();
      } else {
        return destinationBankAccount_ == null ?
            br.com.rbcti.protobuf.artifacts.BankAccount.getDefaultInstance() : destinationBankAccount_;
      }
    }
    /**
     * <code>.bank.BankAccount destination_bank_account = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.rbcti.protobuf.artifacts.BankAccount, br.com.rbcti.protobuf.artifacts.BankAccount.Builder, br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder> 
        getDestinationBankAccountFieldBuilder() {
      if (destinationBankAccountBuilder_ == null) {
        destinationBankAccountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.rbcti.protobuf.artifacts.BankAccount, br.com.rbcti.protobuf.artifacts.BankAccount.Builder, br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder>(
                getDestinationBankAccount(),
                getParentForChildren(),
                isClean());
        destinationBankAccount_ = null;
      }
      return destinationBankAccountBuilder_;
    }

    private float feeAmount_ ;
    /**
     * <code>float fee_amount = 6;</code>
     * @return The feeAmount.
     */
    @java.lang.Override
    public float getFeeAmount() {
      return feeAmount_;
    }
    /**
     * <code>float fee_amount = 6;</code>
     * @param value The feeAmount to set.
     * @return This builder for chaining.
     */
    public Builder setFeeAmount(float value) {

      feeAmount_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>float fee_amount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFeeAmount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      feeAmount_ = 0F;
      onChanged();
      return this;
    }

    private double amountTransfer_ ;
    /**
     * <code>double amount_transfer = 7;</code>
     * @return The amountTransfer.
     */
    @java.lang.Override
    public double getAmountTransfer() {
      return amountTransfer_;
    }
    /**
     * <code>double amount_transfer = 7;</code>
     * @param value The amountTransfer to set.
     * @return This builder for chaining.
     */
    public Builder setAmountTransfer(double value) {

      amountTransfer_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double amount_transfer = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmountTransfer() {
      bitField0_ = (bitField0_ & ~0x00000040);
      amountTransfer_ = 0D;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.bank.Status status = 8;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.bank.Status status = 8;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.bank.Status status = 8;</code>
     * @return The status.
     */
    @java.lang.Override
    public br.com.rbcti.protobuf.artifacts.Status getStatus() {
      br.com.rbcti.protobuf.artifacts.Status result = br.com.rbcti.protobuf.artifacts.Status.forNumber(status_);
      return result == null ? br.com.rbcti.protobuf.artifacts.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.bank.Status status = 8;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(br.com.rbcti.protobuf.artifacts.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.bank.Status status = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000080);
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString authenticationCode_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes authentication_code = 9;</code>
     * @return The authenticationCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAuthenticationCode() {
      return authenticationCode_;
    }
    /**
     * <code>bytes authentication_code = 9;</code>
     * @param value The authenticationCode to set.
     * @return This builder for chaining.
     */
    public Builder setAuthenticationCode(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      authenticationCode_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>bytes authentication_code = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthenticationCode() {
      bitField0_ = (bitField0_ & ~0x00000100);
      authenticationCode_ = getDefaultInstance().getAuthenticationCode();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bank.FundTransfer)
  }

  // @@protoc_insertion_point(class_scope:bank.FundTransfer)
  private static final br.com.rbcti.protobuf.artifacts.FundTransfer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.rbcti.protobuf.artifacts.FundTransfer();
  }

  public static br.com.rbcti.protobuf.artifacts.FundTransfer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FundTransfer>
      PARSER = new com.google.protobuf.AbstractParser<FundTransfer>() {
    @java.lang.Override
    public FundTransfer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FundTransfer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FundTransfer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.rbcti.protobuf.artifacts.FundTransfer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

