// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank_transactions.proto

package br.com.rbcti.protobuf.artifacts;

public interface FundTransferOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bank.FundTransfer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.common.DateTime transfer_date = 1;</code>
   * @return Whether the transferDate field is set.
   */
  boolean hasTransferDate();
  /**
   * <code>.common.DateTime transfer_date = 1;</code>
   * @return The transferDate.
   */
  br.com.rbcti.protobuf.artifacts.DateTime getTransferDate();
  /**
   * <code>.common.DateTime transfer_date = 1;</code>
   */
  br.com.rbcti.protobuf.artifacts.DateTimeOrBuilder getTransferDateOrBuilder();

  /**
   * <code>.bank.Bank source_bank = 2;</code>
   * @return Whether the sourceBank field is set.
   */
  boolean hasSourceBank();
  /**
   * <code>.bank.Bank source_bank = 2;</code>
   * @return The sourceBank.
   */
  br.com.rbcti.protobuf.artifacts.Bank getSourceBank();
  /**
   * <code>.bank.Bank source_bank = 2;</code>
   */
  br.com.rbcti.protobuf.artifacts.BankOrBuilder getSourceBankOrBuilder();

  /**
   * <code>.bank.BankAccount source_bank_account = 3;</code>
   * @return Whether the sourceBankAccount field is set.
   */
  boolean hasSourceBankAccount();
  /**
   * <code>.bank.BankAccount source_bank_account = 3;</code>
   * @return The sourceBankAccount.
   */
  br.com.rbcti.protobuf.artifacts.BankAccount getSourceBankAccount();
  /**
   * <code>.bank.BankAccount source_bank_account = 3;</code>
   */
  br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder getSourceBankAccountOrBuilder();

  /**
   * <code>.bank.Bank destination_bank = 4;</code>
   * @return Whether the destinationBank field is set.
   */
  boolean hasDestinationBank();
  /**
   * <code>.bank.Bank destination_bank = 4;</code>
   * @return The destinationBank.
   */
  br.com.rbcti.protobuf.artifacts.Bank getDestinationBank();
  /**
   * <code>.bank.Bank destination_bank = 4;</code>
   */
  br.com.rbcti.protobuf.artifacts.BankOrBuilder getDestinationBankOrBuilder();

  /**
   * <code>.bank.BankAccount destination_bank_account = 5;</code>
   * @return Whether the destinationBankAccount field is set.
   */
  boolean hasDestinationBankAccount();
  /**
   * <code>.bank.BankAccount destination_bank_account = 5;</code>
   * @return The destinationBankAccount.
   */
  br.com.rbcti.protobuf.artifacts.BankAccount getDestinationBankAccount();
  /**
   * <code>.bank.BankAccount destination_bank_account = 5;</code>
   */
  br.com.rbcti.protobuf.artifacts.BankAccountOrBuilder getDestinationBankAccountOrBuilder();

  /**
   * <code>float fee_amount = 6;</code>
   * @return The feeAmount.
   */
  float getFeeAmount();

  /**
   * <code>double amount_transfer = 7;</code>
   * @return The amountTransfer.
   */
  double getAmountTransfer();

  /**
   * <code>.bank.Status status = 8;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.bank.Status status = 8;</code>
   * @return The status.
   */
  br.com.rbcti.protobuf.artifacts.Status getStatus();

  /**
   * <code>bytes authentication_code = 9;</code>
   * @return The authenticationCode.
   */
  com.google.protobuf.ByteString getAuthenticationCode();
}
